apps/core/urls.py
from django.urls import path
from .views import Home, user_create, UserCreateFormView, user_delete, UserLoginFormView, user_login, UserUpdateFormView, user_update, user_logout

app_name = "core-managment"

urlpatterns = [
    path(r'', Home.as_view(), name="home"),
    path(r'registerform/', UserCreateFormView.as_view(), name="user-register-form"),
    path(r'editform/<int:pk>', UserUpdateFormView.as_view(), name="user-edit-form"),
    path(r'edit/<int:pk>', user_update, name="user-update"),
    path(r'loginform/', UserLoginFormView.as_view(), name="user-login-form"),
    path(r'register/', user_create, name="user-register"),
    path(r'delete/', user_delete, name="user-delete"),
    path(r'login/', user_login, name="user-login"),
    path(r'logout/', user_logout, name="user-logout"),
]

practicabackend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('apps.core.urls', namespace='core-managment')),
    path(r'api/user/', include('apps.core.api.urls', namespace='api-user')),
    path(r'admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Regna Bootstrap Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Bootstrap CSS File -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/jquery/css/jquery-confirm.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-dark bg-dark">
    <!-- Navbar content -->
    <div class="row col-md-12">
        <div class="col-md-5">
            <a class="navbar-brand text-white">Practica Backend</a>
        </div>
        <div class="col-md-3 text-center">
            {% if user.is_authenticated %}
            <span class="text-white">Usuario: {{user}}</span>
            {% endif %}
        </div>

        <div class="col-md-2 text-right">
            <button class="create-user btn-sm btn-primary" type="button" name="button">Create User</button>
        </div>

        <div class="col-md-2 text-left">
            {% if user.is_authenticated %}
            <button class="logout-user btn-sm btn-primary" type="button" name="button">Logout</button>
            {% else %}
            <button class="login-user btn-sm btn-primary" type="button" name="button">Login</button>
            {% endif %}
        </div>


    </div>
</nav>

<div class="row">
    <div class="col-md-12">
        {% block content %}
        {% endblock %}
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

<!-- JavaScript Libraries -->
<script src="{% static 'vendor/jquery/js/jquery.min.js' %}"></script>
<script src="{% static 'vendor/jquery/js/jquery-confirm.js' %}"></script>
<script src="{% static 'vendor/jquery/js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script>
    $(document).ready(function () {

        // Al clickar el botón de borrar usuario

        $(".delete-user").click(function () {
            var data = {pk: $(this).attr("pk"), csrfmiddlewaretoken: '{{ csrf_token }}'};
            $.confirm({
                title: 'Are you sure?',
                content: 'Are you sure to delete this user?',
                buttons: {
                    confirm: function () {
                        $.ajax({
                            url: "{% url 'core-managment:user-delete' %}",
                            token: '{{csrf_token}}',
                            data: data,
                            type: 'POST',
                            success: function (data) {
                                location.reload();
                            },
                            error: function (data) {
                                alert(data.responseText);
                            }
                        });
                    },
                    cancel: function(){

                    }
                }
            });
        });

        // Al clicker al boton de crear usuario, mostramos form en el modal

        $(".create-user").click(function () {
            $.ajax({
                url: "{% url 'core-managment:user-register-form' %}",
                success: function (data) {
                    $(".modal-content").html(data);
                    $("#modal").modal('show');
                    $(".formCreate").submit(function (e) {
                        e.preventDefault();
                        $.ajax({
                            url: "{% url 'core-managment:user-register' %}",
                            type: 'POST',
                            data: $(".formCreate").serialize(),
                            success: function (resp) {
                                location.reload();
                            },
                            error: function (resp) {
                                if(resp.responseText.includes("phonenumber")){
                                    alert("The number must contain a extension. Example: +34603490732");
                                }else{
                                    alert(resp.responseText);
                                }
                            }
                        });
                    });
                },
            });
        });

        // Al clicker al boton de editar usuario, mostramos form en el modal

        $(".edit-user").click(function () {
            var pk = $(this).attr("pk");
            $.ajax({
                url: "{% url 'core-managment:user-edit-form' pk=1 %}".replace(/1/, pk.toString()),
                success: function (resp) {
                    $(".modal-content").html(resp);
                    $("#modal").modal('show');
                    $(".formCreate").submit(function (e) {
                        e.preventDefault();
                        $.ajax({
                            url: "{% url 'core-managment:user-update' pk=1 %}".replace(/1/, pk.toString()),
                            type: 'POST',
                            data: $(".formCreate").serialize(),
                            success: function (resp) {
                                location.reload();
                            },
                            error: function (resp) {
                                if(resp.responseText.includes("phonenumber")){
                                    alert("The number must contain a extension. Example: +34603490732");
                                }else{
                                    alert(resp.responseText);
                                }
                            }
                        });
                    });
                },
                error: function (resp) {
                    alert(resp.responseText);
                }
            });
        });

        // Al clicker al boton de login usuario, mostramos form en el modal

        $(".login-user").click(function () {
            $.ajax({
                url: "{% url 'core-managment:user-login-form' %}",
                success: function (data) {
                    $(".modal-content").html(data);
                    $("#modal").modal('show');
                    $(".formCreate").submit(function (e) {
                        e.preventDefault();
                        $.ajax({
                            url: "{% url 'core-managment:user-login' %}",
                            type: 'post',
                            data: $(".formCreate").serialize(),
                            success: function (resp) {
                                location.reload();
                            },
                            error: function (resp) {
                                alert(resp.responseText);
                            }
                        });
                    });
                },
            });
        });

        // Al clicker al boton de logout usuario, nos salimos directamente de sesión

        $(".logout-user").click(function () {
            var data = {csrfmiddlewaretoken: '{{ csrf_token }}'};
            $.ajax({
                type: 'POST',
                url: "{% url 'core-managment:user-logout' %}",
                data: data,
                success: function (resp) {
                    location.reload();
                },
            });
        });

    });


</script>


</body>
</html>